/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class SearchUserPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form SearchUserPanelDesign
     */
    public SearchUserPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsername = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        jFollowbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 255));
        setLayout(null);

        jUsername.setText("jLabel1");
        add(jUsername);
        jUsername.setBounds(90, 60, 51, 20);

        jPhoto.setText("jLabel2");
        add(jPhoto);
        jPhoto.setBounds(80, 150, 200, 130);

        jFollowbtn.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jFollowbtn.setText("FOLLOW");
        add(jFollowbtn);
        jFollowbtn.setBounds(460, 100, 170, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jFollowbtn;
    public javax.swing.JLabel jPhoto;
    public javax.swing.JLabel jUsername;
    // End of variables declaration//GEN-END:variables
}
