
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADITI SURI
 */
public class UserChangePasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserChangePasswordFrame
     */
    public UserChangePasswordFrame(String username) {
        String user;
        initComponents();
        user = username;
        jUsername.setText(user);
        jUsername.setEditable(false);
        setSize(800, 800);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jOldPass = new javax.swing.JPasswordField();
        jNewPass = new javax.swing.JPasswordField();
        jConfirmPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("CHANGE PASSWORD HERE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 310, 70);

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 140, 110, 20);

        jLabel3.setText("OLD PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 210, 121, 30);

        jLabel4.setText("NEW PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 300, 124, 20);

        jLabel5.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 370, 159, 20);
        getContentPane().add(jUsername);
        jUsername.setBounds(340, 140, 220, 30);
        getContentPane().add(jOldPass);
        jOldPass.setBounds(340, 210, 220, 26);
        getContentPane().add(jNewPass);
        jNewPass.setBounds(340, 280, 220, 26);
        getContentPane().add(jConfirmPass);
        jConfirmPass.setBounds(340, 360, 220, 26);

        jButton1.setText("CHANGE PASSWORD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 460, 190, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //get all data
        String username = jUsername.getText();
        String oldPass = jOldPass.getText();
        String newPass = jNewPass.getText();
        String confirmPass = jConfirmPass.getText();
        if (username.isEmpty() || newPass.isEmpty() || oldPass.isEmpty() || confirmPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields Required");
        } else if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Your Passwords do not match");
        } else {

            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/UserChangePassword")
                        .queryString("username", username)
                        .queryString("oldpassword", oldPass)
                        .queryString("newpassword", newPass)
                        .asString();
                if (res.getStatus() == 200) {
                    String response = res.getBody();
                    if (response.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Password change Successfull");
                        dispose();
                        UserLoginFrame obj = new UserLoginFrame();
                    } else {
                        JOptionPane.showMessageDialog(this, "Try again");
                    }
                }

            } catch (Exception e) {
                e.printStackTrace();;
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserChangePasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserChangePasswordFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jConfirmPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jNewPass;
    private javax.swing.JPasswordField jOldPass;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
