
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADITI SURI
 */
public class UserForgotPasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserForgotPasswordFrame
     */
    String responseOtp = "";
    String username;
    public UserForgotPasswordFrame() {
        initComponents();
        setSize(800, 800);
        setVisible(true);
        jPanel1.setBounds(100, 100, 1000, 500);
        jPanel1.setVisible(true);
        jPanel2.setBounds(100, 100, 1000, 500);
        jPanel2.setVisible(false);
        jPanel3.setBounds(100, 100, 1000, 500);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userOtp = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jnewpass = new javax.swing.JPasswordField();
        jconfirmpass = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setText("ENTER USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 34, 320, 80);
        jPanel1.add(jUsername);
        jUsername.setBounds(390, 50, 430, 40);

        jButton1.setBackground(new java.awt.Color(0, 153, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 120, 320, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 920, 210);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel2.setText("ENTER OTP");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(32, 38, 280, 60);
        jPanel2.add(userOtp);
        userOtp.setBounds(410, 40, 420, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("PROCEED");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(260, 130, 310, 70);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 230, 920, 220);

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel3.setText("NEW PASSWORD");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(15, 16, 300, 50);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 80, 380, 40);
        jPanel3.add(jnewpass);
        jnewpass.setBounds(410, 20, 340, 40);
        jPanel3.add(jconfirmpass);
        jconfirmpass.setBounds(410, 90, 340, 40);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(270, 150, 310, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 460, 920, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         username = jUsername.getText();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter your username");
        }
        try {
            HttpResponse<String> res = Unirest.get("http://localhost:8999/ForgotPasswordCheck")
                    .queryString("username", username)
                    .asString();
            if (res.getStatus() == 200) {
                String response = res.getBody();
                if (response.equals("fails")) {
                    JOptionPane.showMessageDialog(this, "PLEASE TRY AGAIN");
                } else {
                    responseOtp = response;
                    System.out.println(response);
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(true);
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String userotp = userOtp.getText();
        if (userotp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid otp");
        } else if (responseOtp.equals(userotp)) {
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String newpassword = jnewpass.getText();
        String confirmpass = jconfirmpass.getText();
        if (newpassword.isEmpty() || confirmpass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields Required");
        } else if (!newpassword.equals(confirmpass)) {
            JOptionPane.showMessageDialog(this, "your passwords dont match");
        } else {
            try {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/ForgotPasswordChange")
                        .queryString("newpassword", newpassword)
                        .queryString("username", username)
                        .asString();
                if(res.getStatus()==200){
                    String response=res.getBody();
                    if(response.equals("success")){
                        JOptionPane.showMessageDialog(this, "Password changed successfully");
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "An error occurred");
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForgotPasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jUsername;
    private javax.swing.JPasswordField jconfirmpass;
    private javax.swing.JPasswordField jnewpass;
    private javax.swing.JTextField userOtp;
    // End of variables declaration//GEN-END:variables
}
