/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class UserFollowingPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form UserFollowingPanelDesign
     */
    public UserFollowingPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jusername = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        jUnfollow = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);
        add(jusername);
        jusername.setBounds(330, 40, 160, 50);
        add(jPhoto);
        jPhoto.setBounds(70, 120, 160, 140);

        jUnfollow.setText("UNFOLLOW");
        jUnfollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnfollowActionPerformed(evt);
            }
        });
        add(jUnfollow);
        jUnfollow.setBounds(350, 180, 160, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jUnfollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnfollowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnfollowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jPhoto;
    public javax.swing.JButton jUnfollow;
    public javax.swing.JLabel jusername;
    // End of variables declaration//GEN-END:variables
}
