/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class UserFollowingPostsPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserFollowingPostsPanel
     */
    public UserFollowingPostsPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        jLike = new javax.swing.JLabel();
        jLikebtn = new javax.swing.JButton();
        jCaption = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        jLabel1.setText("BY");
        add(jLabel1);
        jLabel1.setBounds(130, 20, 50, 30);
        add(jPhoto);
        jPhoto.setBounds(50, 70, 210, 160);
        add(jLike);
        jLike.setBounds(140, 250, 70, 30);

        jLikebtn.setText("LIKE");
        add(jLikebtn);
        jLikebtn.setBounds(30, 250, 65, 29);

        jCaption.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(jCaption);
        jCaption.setBounds(360, 130, 120, 40);

        jName.setText("jLabel2");
        add(jName);
        jName.setBounds(280, 30, 160, 40);
        add(jDate);
        jDate.setBounds(260, 250, 140, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jCaption;
    public javax.swing.JLabel jDate;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLike;
    public javax.swing.JButton jLikebtn;
    public javax.swing.JLabel jName;
    public javax.swing.JLabel jPhoto;
    // End of variables declaration//GEN-END:variables
}
