
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADITI SURI
 */
public class UserMyFollowers extends javax.swing.JFrame {

    /**
     * Creates new form UserMyFollowers
     */
    String user;

    Dimension d;

    public UserMyFollowers(String username) {
        initComponents();
        user = username;
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.getSize());
        setVisible(true);
        getMyFollowers();
//          jScrollPane1.setSize(d.width - 300, d.height - 300);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 24)); // NOI18N
        jLabel1.setText("FOLLOWERS LIST!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 0, 280, 90);

        mainPanel.setBackground(new java.awt.Color(51, 255, 204));
        mainPanel.setLayout(null);
        jScrollPane1.setViewportView(mainPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 810, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void getMyFollowers() {
        try {
            HttpResponse<String> res = Unirest.get(GlobalClass.serverAddress + "myFollowers")
                    .queryString("loggedinuser", user)
                    .asString();
            if (res.getStatus() == 200) {
                String response = res.getBody();
                System.out.println(response);
                if (response.equals("fails")) {
                    JOptionPane.showMessageDialog(this, "No Followers!!!!");
                } else {
                    System.out.println("Response---->" + response);
                    StringTokenizer st = new StringTokenizer(response, "~~");
                    int count = st.countTokens();
                    //mainPanel.removeAll();
                    mainPanel.setPreferredSize(new Dimension(d.width - 300, count * 330));
                    UserFollowerPanelDesign obj[] = new UserFollowerPanelDesign[count];
                    int x = 10, y = 10;
                    for (int i = 0; i < count; i++) {
                        final int a = i;
                        String userToken = st.nextToken();
                        StringTokenizer st2 = new StringTokenizer(userToken, ";;");
                        String username = st2.nextToken();
                        String photoPath = st2.nextToken();
                        String id = st2.nextToken();

                        System.out.println("username----->" + username);
                        System.out.println("photoPath---->" + photoPath);
                        obj[i] = new UserFollowerPanelDesign();
                        obj[i].jUsername.setText(username);
                        obj[i].jPhoto.setText(photoPath);
                        obj[i].jRemove.addActionListener(new ActionListener() {

                            @Override
                            public void actionPerformed(ActionEvent e) {
                                //send Unirest get request on a resource removeFollower with id 
                                try {
                                    HttpResponse<String> res = Unirest.get(GlobalClass.serverAddress+"removeFollower")
                                            .queryString("followerId", id)
                                            .asString();
                                    if (res.getStatus() == 200) {
                                        String response = res.getBody();
                                        if (response.equals("success")) {
                                            getMyFollowers();
                                        }
                                    }
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                            }
                        });

                        obj[i].setBounds(x, y, 800, 300);

                        mainPanel.add(obj[i]);
                        y += 300;
                        mainPanel.repaint();
                        obj[i].repaint();
                    }
                    mainPanel.repaint();

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMyFollowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMyFollowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMyFollowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMyFollowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMyFollowers("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
