/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class UserPostPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form UserPostPanelDesign
     */
    public UserPostPanelDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDate = new javax.swing.JLabel();
        jCaption = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        jaddStorybtn = new javax.swing.JButton();
        jDeletebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 153));
        setLayout(null);
        add(jDate);
        jDate.setBounds(100, 20, 360, 50);
        add(jCaption);
        jCaption.setBounds(20, 230, 300, 60);
        add(jPhoto);
        jPhoto.setBounds(20, 80, 170, 150);

        jaddStorybtn.setText("ADD STORY");
        jaddStorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddStorybtnActionPerformed(evt);
            }
        });
        add(jaddStorybtn);
        jaddStorybtn.setBounds(400, 130, 160, 60);

        jDeletebtn.setText("DELETE POST");
        add(jDeletebtn);
        jDeletebtn.setBounds(400, 220, 160, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jaddStorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddStorybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaddStorybtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jCaption;
    public javax.swing.JLabel jDate;
    public javax.swing.JButton jDeletebtn;
    public javax.swing.JLabel jPhoto;
    public javax.swing.JButton jaddStorybtn;
    // End of variables declaration//GEN-END:variables
}
