/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class UserFollowerPanelDesign extends javax.swing.JPanel {

    /**
     * Creates new form UserFollowerPanelDesign
     */
    public UserFollowerPanelDesign() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPhoto = new javax.swing.JLabel();
        jUsername = new javax.swing.JLabel();
        jRemove = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(null);
        add(jPhoto);
        jPhoto.setBounds(41, 81, 150, 130);
        add(jUsername);
        jUsername.setBounds(300, 40, 200, 50);

        jRemove.setText("REMOVE FOLLOWER");
        jRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveActionPerformed(evt);
            }
        });
        add(jRemove);
        jRemove.setBounds(300, 160, 180, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveActionPerformed
        // TODOjRemover handling code here:
    }//GEN-LAST:event_jRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    public javax.swing.JLabel jPhoto;
    public javax.swing.JButton jRemove;
    public javax.swing.JLabel jUsername;
    // End of variables declaration//GEN-END:variables
}