
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.util.StringTokenizer;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ADITI SURI
 */
public class UserSearchFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserSearchFrame
     */
    String user;
    Dimension d;

    public UserSearchFrame(String username) {
        initComponents();
        user = username;
        d = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(d.getSize());
        jScrollPane1.setSize(d.width - 300, d.height - 300);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKeyword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jKeyword);
        jKeyword.setBounds(50, 80, 320, 26);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 80, 93, 29);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SEARCH USER HERE TO FOLLOW!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 420, 50);

        mainPanel.setBackground(new java.awt.Color(153, 255, 255));
        mainPanel.setLayout(null);
        jScrollPane1.setViewportView(mainPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 600, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //get keyword
        String keyword = jKeyword.getText();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error.\n Please type a username to search!!");
        } //send unirest get request on resoucre searchUser
        //logged in username
        //keyword
        else {
            try {
                try {
                    HttpResponse<String> res = Unirest.get("http://localhost:8999/searchUser")
                            .queryString("username", user)
                            .queryString("keyword", keyword)
                            .asString();
                    if (res.getStatus() == 200) {
                        String response = res.getBody();
                        if (response.equals("fails")) {
                            JOptionPane.showMessageDialog(this, "No Such user exists");

                        } else {
                            System.out.println("Response---->" + response);

                            StringTokenizer st = new StringTokenizer(response, "$$");
                            int count = st.countTokens();
                            mainPanel.removeAll();
                            mainPanel.setPreferredSize(new Dimension(d.width - 300, count * 330));
                            SearchUserPanelDesign obj[] = new SearchUserPanelDesign[count];
                            int x = 10, y = 10;
                            for (int i = 0; i < count; i++) {
                                final int a=i;
                                String userToken = st.nextToken();
                                StringTokenizer st2 = new StringTokenizer(userToken, ",,");
                                String username = st2.nextToken();
                                String photoPath = st2.nextToken();
                                String ifFollow=st2.nextToken();
                                System.out.println("username----->" + username);
                                System.out.println("photoPath---->" + photoPath);
                                System.out.println("ifFollow---->"+ifFollow);
                                obj[i] = new SearchUserPanelDesign();
                                obj[i].jUsername.setText(username);
                              //  obj[i].jPhoto.setText(photoPath);
                                try {
                    URL url = new URL(GlobalClass.serverAddress + "GetResource/" + photoPath);
                    //System.out.println("Path of Image Stored in server side--------------" + url);
                    BufferedImage img = ImageIO.read(url);
                    Image resizedimage = img.getScaledInstance(obj[i].jPhoto.getWidth(), obj[i].jPhoto.getHeight(), Image.SCALE_SMOOTH);
                    obj[i].jPhoto.setIcon(new ImageIcon(resizedimage));

                } catch (Exception e) {
                    e.printStackTrace();
                }
                                if(ifFollow.equals("yes")){
                                    obj[i].jFollowbtn.setText("FOLLOWING");
                                }
                                obj[i].jFollowbtn.addActionListener(new ActionListener() {

                                    @Override
                                    public void actionPerformed(ActionEvent e) {
                                        //send unirest get request on resouce follow user
                                        try {
                                            HttpResponse<String> res = Unirest.get("http://localhost:8999/followUser")
                                                    .queryString("followby", user)
                                                    .queryString("followto", username)
                                                    .asString();
                                            if (res.getStatus() == 200) {
                                                String response = res.getBody();
                                               if(response.equals("success")){
                                                   obj[a].jFollowbtn.setText("FOLLOWING");
                                               }else{
                                                   obj[a].jFollowbtn.setText("FOLLOW");
                                               }
                                              
                                            }
                                        } catch (Exception e1) {
                                            e1.printStackTrace();
                                        }
                                    }
                                });
                                obj[i].setBounds(x, y, 800, 300);

                                mainPanel.add(obj[i]);
                                y += 300;
                                mainPanel.repaint();
                                obj[i].repaint();
                            }
                            mainPanel.repaint();
                        }
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSearchFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jKeyword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
