
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.io.File;
import javax.swing.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADITI SURI
 */
public class UserSignUp extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
     File f;
    public UserSignUp() {
        initComponents();
         setSize(800,800);
         jbg.setBounds(0, 0, 800, 800);
         ImageIcon icon = new ImageIcon("src/uploads/white.jpg");
            Image resizedimg = icon.getImage().getScaledInstance(jbg.getWidth(), jbg.getHeight(), Image.SCALE_SMOOTH);
            jbg.setIcon(new ImageIcon(resizedimg));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPhoto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jConfirmPass = new javax.swing.JPasswordField();
        jPassword = new javax.swing.JPasswordField();
        jPhone = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jUsername = new javax.swing.JTextField();
        jMale = new javax.swing.JRadioButton();
        jFemale = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("WELCOME TO INSTAGRAM!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 540, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SIGNUP HERE!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 90, 200, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("USERNAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 140, 120, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 160, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 260, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 300, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 350, 210, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("GENDER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 390, 170, 70);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PHOTO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 430, 150, 80);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 450, 120, 40);

        jPhoto.setBackground(new java.awt.Color(0, 255, 255));
        jPhoto.setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jPhoto);
        jPhoto.setBounds(350, 450, 220, 120);

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("SIGN UP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 570, 280, 50);
        getContentPane().add(jConfirmPass);
        jConfirmPass.setBounds(290, 360, 340, 40);
        getContentPane().add(jPassword);
        jPassword.setBounds(290, 310, 340, 40);
        getContentPane().add(jPhone);
        jPhone.setBounds(290, 260, 340, 40);
        getContentPane().add(jEmail);
        jEmail.setBounds(290, 210, 340, 40);
        getContentPane().add(jUsername);
        jUsername.setBounds(290, 150, 340, 40);

        buttonGroup1.add(jMale);
        jMale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jMale.setText("Male");
        getContentPane().add(jMale);
        jMale.setBounds(290, 410, 71, 29);

        buttonGroup1.add(jFemale);
        jFemale.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jFemale.setText("Female");
        getContentPane().add(jFemale);
        jFemale.setBounds(430, 410, 91, 29);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADITI SURI\\Downloads\\signup.png")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 580, 320, 120);

        jbg.setText("jLabel10");
        getContentPane().add(jbg);
        jbg.setBounds(0, 0, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String username=jUsername.getText();
       String email=jEmail.getText();
        String password=jPassword.getText();
        String password2=jConfirmPass.getText();
        String phone=jPhone.getText();
        String gender="";
        if(jMale.isSelected()){
            gender="Male";
        }
        else if (jFemale.isSelected()){
            gender="Female";
        }
        if (username.isEmpty()|| password.isEmpty()||password.isEmpty()||email.isEmpty()||password2.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"All fields are required.");
        }
        else if(!email.contains("@")&&email.contains(".")){
            JOptionPane.showMessageDialog(this,"Please enter a valid email address.");
        }
        else if(phone.length()!=10){
            JOptionPane.showMessageDialog(this,"Please enter a 10 digit PhoneNumber.");
        }
         else if(!password.equals(password2)){
             JOptionPane.showMessageDialog(this,"Your passwords do not match");
        }
        else if(f==null){
              JOptionPane.showMessageDialog(this,"Please Choose a photo");
        }
       
        else{
            //send unirest post request on server on resource UserSignup
        try{
          HttpResponse<String> res;
            res = Unirest.post("http://localhost:8999/UserSignUp")
                    .queryString("username",username)//key value
                    .queryString("email",email)
                    .queryString("password",password)
                    .queryString("phone",phone)
                    .queryString("gender",gender)
                    .field("photo",f)
                    .asString();
          if(res.getStatus()==200){
              String response=res.getBody();
              if(response.equals("success")){
                  JOptionPane.showMessageDialog(this, "SignUp Successful");
                                 dispose();
              }else{
                   JOptionPane.showMessageDialog(this, "Username already exists. Please Signup with a different username");
    
                   UserLoginFrame obj=new UserLoginFrame();
              }
          }
          
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFileChooser chooser = new JFileChooser();
        int ans = chooser.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.getPath());
            Image resizedimg = icon.getImage().getScaledInstance(jPhoto.getWidth(), jPhoto.getHeight(), Image.SCALE_SMOOTH);
            jPhoto.setIcon(new ImageIcon(resizedimg));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPasswordField jConfirmPass;
    private javax.swing.JTextField jEmail;
    private javax.swing.JRadioButton jFemale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jMale;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jPhone;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jbg;
    // End of variables declaration//GEN-END:variables
}
